name: buildx

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches: main
  push:
    branches:
     - main
    tags:
      - v*

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=kkent4g/airflow-sample-arm
          VERSION=edge
          REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          if [[ "${{ github.ref }}"  == refs/tags/* ]]; then
            VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/v##g")
          fi
          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION=nightly
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest"
          fi
          echo ::set-output name=tags::${TAGS}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      -
        name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build ARM64 Image and push
        id: docker_build_arm64
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          build-args: |
            PYTHON_VERSION=3.8
            AIRFLOW_VERSION=2.0.2
            AIRFLOW_UID=1000
            AIRFLOW_GID=1000
